name: Comment on PR Based on Test Result

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Fetch_PR:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.A_TOKEN }}

      - name: Reassign Custom Codeowners for Renovatebot PRs
        uses: expdemo/proj-B@main
        with:
          org_repo: ${{ github.repository }}
          github_token: ${{ secrets.B_TOKEN }}
          PR_details: ${{ github.event.pull_request.number }}
