name: SHA

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  gitsha: ""

jobs:
  Fetch_PR:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v3

      - name: GET SHA
        run: |
          echo "xyz=${{ github.sha }}" >> "env.gitsha"
          echo $xyz
          echo ${{ gitsha }}
  Fetch_SHA:
    runs-on: ubuntu-latest
    needs: Fetch_PR
    steps:
      - name: GET SHA
        run: echo $env.gitsha
        
